/**********************
 *                    *
 *      typpi.js      *
 *                    *
 **********************/
// Random name generator module

// TODO:
// parse values from .csv
prefix = ['Bjúgna',
          'Pylsu',
          'Epla',
          'Eitur',
          'Typpa',
          'Fugla',
          'Vél-',
          'Gúrku',
          'Tungl',
          'Þang',
          'Stál',
          'Barna',
          'Salt',
          'Eðlu',
          'Sveskju',
          'Skúffu',
          'Sorgar',
          'Gleði',
          'Saur',
          'Þarma',
          'Kakó',
          'Kaffi',
          'Svína',
          'Ellilífeyris',
          'Forsendu',
          'Legvatns',
          'Sveppa',
          'blog.central.is/',
          'Drasl',
          'Ógeðs',
          'Truntu',
          'Frussu',
          'Pussu',
          'Fröllu',
          'Ljóða',
          'Krabba',
          'Rusla',
          'Fiski',
          'Hárgreiðslu',
          'Niðursuðu',
          'Sjávarútvegs',
          'Líftækni',
          'Tauga',
          'Taugaveiklunar',
          'Móðursýkis',
          'Bauna',
          'Stjórnmála',
          'Forseta'];

postfix = ['maður',
           'sali',
           'mauk',
           'hrúga',
           'messa',
           'land.is',
           'flaska',
           'fótur',
           'grautur',
           'haus',
           'kaka',
           'partí',
           'samkoma',
           'samfélag',
           'söfnuður',
           'sölumaður',
           'bóndi',
           'fíkill',
           'bolla',
           'bolli',
           'vatn',
           'skjaldborgin',
           'brestur',
           'neytandi',
           'elskhugi',
           'Group hf.',
           'prestur',
           'sinnep',
           'pylsa',
           'fræðingur',
           'tæknir',
           'dúlla',
           'krútt',
           'sprengja',
           'skvísa',
           'hönnuður',
           'listamaður',
           'verkfræðingur',
           'smiður',
           'Prinsessa69@hotmail.com',
           'menni',
           'læknir',
           'frömuður',
           'frumkvöðull'];

exports.random  = function()
{
    return prefix[Math.floor(Math.random() * prefix.length)] + 
           postfix[Math.floor(Math.random() * postfix.length)];
}


